spring.application.name= atol-integration-service
logging.charset.console=UTF-8
atol.api.url =https://testonline.atol.ru/possystem/v5
atol.api.login= ${ATOL_LOGIN}
atol.api.pass=${ATOL_PASSWORD}
atol.api.group-code=${ATOL_GROUPCODE}

spring.datasource.url=jdbc:postgresql://localhost:5432/atol_db
spring.datasource.username=postgres
spring.datasource.password=postgres

